### ISSUE TITLE
Does not compile with rust 1.87.0

### ISSUE THREAD

**Issue by baitcode** [0xSpaceShard/starknet-devnet#786]
**Describe the bug (observed vs expected behavior)**

I'm trying to use starknet-devnet as a library crate to spawn a background server process. I'm using rust v1.87.0

`cargo build` gives following output:

```
error[E0308]: mismatched types
  --> /Users/baitcode/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cairo-vm-1.0.2/src/hint_processor/builtin_hint_processor/signature.rs:32:25
   |
32 |         .is_multiple_of(&(CELLS_PER_SIGNATURE as usize))
   |          -------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `&usize`
   |          |
   |          arguments to this method are incorrect
   |
note: method defined here
  --> /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/num/mod.rs:1218:5
   = note: this error originates in the macro `uint_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider removing the borrow
   |
32 -         .is_multiple_of(&(CELLS_PER_SIGNATURE as usize))
32 +         .is_multiple_of((CELLS_PER_SIGNATURE as usize))
   |

```

**To Reproduce**

1. clone  starknet-devnet repo to a new folder. `cd` into it.
2. rm rust-toolchain.toml
3. rustup default 1.87.0
4. cargo build

**Comment by baitcode** [comment]
It is, but the problem is in different crate.
