### PR TITLE
Update to Starknet 0.13.4 (including RPC 0.8)

### LINKED ISSUE #613: JSON-RPC API 0.8.0 adaptation
- Documentation: 
https://github.com/starkware-libs/starknet-specs/releases/tag/v0.8.0-rc1
- Currently in RC phase: 0.8.0-rc.1
- Subtask PRs should target branch `json-rpc-v0.8.0`
- Requires an adapted Blockifier version (or at least a commit)

## Subtasks

- [x] Error improvements - introduced in #627 
  - failure reason in `getTransactionStatus`
  - structure in execution errors
  - `INSUFFICIENT_MAX_FEE` -> `INSUFFICIENT_RESOURCES_FOR_VALIDATE`
- [ ] Gas consumption changes
- [x] WebSocket API support - introduced in #619
- RPC method additions:
  - [x] `starknet_getCompiledCasm` - introduced in #633
  - [x] `starknet_getStorageProof` - introduced in #659
  - [x] `starknet_getMessagesStatus` - introduced in #621
  - [x] 10 ws-related methods - introduced in several PRs

### LINKED ISSUE #680: Failing tests requiring USC that supports Sierra 1.7.0
Currently our integration forking tests are failing because Devnet can't handle the latest Sierra artifacts. This is the reported error:

```
Sierra compilation error: Unable to compile Sierra to Casm. No matching ContractClass or CasmContractClass found for version 1.7.0: undefined
```

A new version of USC should help. Waiting for:
- https://github.com/software-mansion/universal-sierra-compiler/pull/62
- https://github.com/software-mansion/universal-sierra-compiler/pull/67

### PR DESCRIPTION
**Pull request by FabijanC**
## Usage related changes

- Close #680
- Use Rust 1.85
  - **Breaking**
  - Required by Blockifier
- JSON-RPC API:
  - Close #613
  - Remove support for adding declaration transactions v0 and v1

## Development related changes

- ~~Waiting for starknet-rs to receive RPC 0.8.0 support. Until then, too many of our tests are failing.~~
  - ~~Merging and new version release is thus blocked.~~
  - ~~Basically waiting for this issue to be handled: https://github.com/xJonathanLEI/starknet-rs/issues/674~~

## Checklist:

- [x] Checked out the [contribution guidelines](CONTRIBUTING.md)
- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] No unused dependencies - `./scripts/check_unused_deps.sh`
- [x] No spelling errors - `./scripts/check_spelling.sh`
- [ ] Performed code self-review
- [x] Rebased to the latest commit of the target branch (or merged it into my branch)
    -   Once you make the PR reviewable, please avoid force-pushing
- [ ] Updated the docs if needed - `./website/README.md`
- [x] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) resolvable by this PR - [linking info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [x] Updated the tests if needed; all passing - [execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/main/.github/CONTRIBUTING.md#test-execution)

## Summary by CodeRabbit

- **New Features**
  - Introduced real‑time WebSocket subscription endpoints to receive new blocks, transaction statuses, and event notifications.
  - Added new RPC methods for retrieving compiled contract artifacts and enhanced transaction trace support.
  - Updated the CLI with distinct L1 and L2 gas pricing parameters.
  - Added new methods for handling storage proofs and compiling CASM code.
  - Introduced a new method for creating `L1HandlerTransaction` with an optional L1 transaction hash.

- **Improvements**
  - Upgraded the Rust toolchain and Docker environment for improved performance and security.
  - Refined transaction processing and error handling for clearer feedback.
  - Updated API specifications to OpenRPC version 0.8.0.
  - Enhanced test coverage for error handling in RPC methods.
  - Improved error handling in transaction declaration and deployment processes.

- **Chores**
  - Modernized dependency versions and performed extensive internal refactoring for better maintainability.
  - Removed deprecated transaction types and streamlined the transaction handling logic.

### CODE REVIEW

**Comment by FabijanC** [comment]
@coderabbitai configuration

**Comment by FabijanC** [comment]
@coderabbit How do I configure you to skip files in `crates/starknet-devnet-server/test_data/spec/`?
